### ISSUE TITLE
Runtime error, compile warning unresolved generic argument being passed with PassGenerics attribute

### ISSUE THREAD

**Issue by bohdanszymanik** [SAFE-Stack/SAFE-BookStore#267] opened 2018-01-17 19:19 UTC
### Description

On two Win 10 workstations with I've experienced the behaviour that when cloning building and running (build.cmd run) there is a compile warning and a runtime error that means that the Bookstore fails to display in a browser.

### Repro steps

1. Clone

2. build.cmd run

### Expected behavior

The SAFE-Bookstore loads in a browser.

### Actual behavior

The browser shows a white/blank page.

The build process finishes with the following warning:
WARNING in ./App.fs
C:/wd/safe/SAFE-BookStore/src/Client/App.fs(8,18): (8,24) warning FABLE: An unresolved generic argument ('a) is being passed to a function with `PassGenericsAttribute`. This will likely fail at runtime. Try adding `PassGenericsAttribute` to the calling method or using concrete types.
 @ ./Client.fsproj 1:0-25
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj
webpack: Compiled with warnings.

In Chrome, in the developer console I see:
Menu.fs:307 Uncaught Error: Cannot deserialize into a - Error (inflate): Cannot resolve generic argument a: TypeError: Cannot read property 'generics' of undefined - Data: '{"UserName":"test","Token":"eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIn0.vrw6hRV6dR_AA7XYW3BnhFOHGBrkM3jXf4IDg1Qg2SlsQGCa4lJrlqD3gPuwTn0AZZIan8MGKXNLRKzE2kYoq_8FMEa6NAN_.oG6usHgaVX3qxdAVdCbzzA.HWSf7Yk9l2jmZfiLC2F3TfftflRS2Gwa8npWZSDo0AI.4pipDmslr6iIOCQyusAl9PUu7UJlIvZNdsUcaUd68YI"}'
    at raise (Menu.fs:307)
    at ofJson (Menu.fs:321)
    at App.fs:8
    at defaultArg (Menu.fs:44)
    at loadUser (App.fs:8)
    at init (App.fs:68)
    at Program.init (App.fs:144)
    at Program.init (navigation.fs:88)
    at Program.traceInit [as init] (program.fs:67)
    at App.fs:53
raise @ Menu.fs:307
ofJson @ Menu.fs:321
(anonymous) @ App.fs:8
defaultArg @ Menu.fs:44
loadUser @ App.fs:8
init @ App.fs:68
(anonymous) @ App.fs:144
init @ navigation.fs:88
traceInit @ program.fs:67
(anonymous) @ App.fs:53
init_1 @ App.fs:53
init @ debugger.fs:44
__exports.runWith @ program.fs:95
__exports.run @ program.fs:123
./App.fs @ App.fs:154
__webpack_require__ @ bootstrap 678e1659c14a7f014b35:678
fn @ bootstrap 678e1659c14a7f014b35:88
./Client.fsproj @ bundle.js:56949
__webpack_require__ @ bootstrap 678e1659c14a7f014b35:678
fn @ bootstrap 678e1659c14a7f014b35:88
0 @ bundle.js:57891
__webpack_require__ @ bootstrap 678e1659c14a7f014b35:678
../../../../../Users/BohdanS/.nuget/packages/fable.core/1.3.7/fable-core/Array.js.__webpack_exports__.b @ bootstrap 678e1659c14a7f014b35:724
(anonymous) @ bootstrap 678e1659c14a7f014b35:724
client?cd17:77 [WDS] Hot Module Replacement enabled.
client?cd17:144 [WDS] Warnings while compiling.
msgWarnings @ client?cd17:144
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
client?cd17:147 ./App.fs
C:/wd/safe/SAFE-BookStore/src/Client/App.fs(8,18): (8,24) warning FABLE: An unresolved generic argument ('a) is being passed to a function with `PassGenericsAttribute`. This will likely fail at runtime. Try adding `PassGenericsAttribute` to the calling method or using concrete types.
 @ ./Client.fsproj 1:0-25
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj
msgWarnings @ client?cd17:147
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957

The error actually occurs on line 59:     Fable.PowerPack.BrowserLocalStorage.load "user"

Prior to the last revision it used to be Utils.load "user"

### Known workarounds

None that I know of

### Related information 

* Win 10
* Branch Master
* Node 9.3.0, Yarn 1.3.2, Fable 1.3.7, .net core 2.1.3, .net framework 4.7.2 also installed

**Comment by forki** [comment] 2018-01-18 07:15
/cc @alfonsogcnunez

Am 17.01.2018 20:24 schrieb "Bohdan Szymanik" <notifications@github.com>:

**Comment by kfrie** [comment] 2018-01-25 16:15
@bohdanszymanik #274 is a duplicate of this and both the error and the compiler warning are solved by #279

**Closed** 2018-01-25 16:17 UTC
